source "https://rubygems.org"

gem "webrick", "~> 1.8" # Required for Ruby 3.1

# If you want to use GitHub Pages, remove the "gem "jekyll"" and
# uncomment the line below. To upgrade, run `bundle update github-pages`.

# gem "jekyll", "~> 4.3.2"
gem "github-pages", "~> 228"

# Theme
gem "just-the-docs"
